### PR TITLE
Faster PlantUML Rendering

### PR DESCRIPTION
**Pull request by river0825**
Use single child_process to render the diagram.

out

### CODE REVIEW

**Comment by shd101wyy** [comment]
@river0825 YOU ARE SUCH A BIG BOSS!  
I will check it when I am free.
I am studying for the final exam, so I will merge your pull request like about week later.  

Thank you very much :)

**Comment by river0825** [comment]
Hi, is there any thing I should do with this pull request ??

**Comment by shd101wyy** [comment]
Hi @river0825 ,  

I have just reviewed your code. 
You don't need to deal with the cache of the graphs yourself because this extension already does caching for you.  
Also, [this line](https://github.com/shd101wyy/markdown-preview-enhanced/pull/403/files#diff-34e5327775bbe3b3b09e1bdd4258fb6cL14) is necessary and shouldn't be changed, otherwise it will cause the [@import issue](https://github.com/shd101wyy/markdown-preview-enhanced/issues/398#issuecomment-300038397).  
Could you please help check [this commit](https://github.com/shd101wyy/markdown-preview-enhanced/commit/a0dc06628684d1f83f445ee877ab14ebbf40eeaf)? I used a `CALLBACKS` queue instead of using hash.  
It would be great if you can help test [this commit](https://github.com/shd101wyy/markdown-preview-enhanced/commit/a0dc06628684d1f83f445ee877ab14ebbf40eeaf) and update your pull request.

Thank you

**Comment by river0825** [comment]
I've tried using callback queue, and it works not well.

I added "CALLBACKS.add" in very first place while generateSVG has been called thus the callback didn't work fine.

Thanks for your code review.

**Comment by shd101wyy** [comment]
So I can merge the pull request now?

**Comment by river0825** [comment]
Yes, please. The code has been replaced with yours.

**Pull request merged**
