### PR TITLE
Fix issue #455

### PR DESCRIPTION
**Pull request by tmori3y2**
HI @shd101wyy !

The height of the svg element is too large against the bounding client rect height of polygon .

I cannot remove these blank except to delete the height of the svg element.

### CODE REVIEW

**Comment by shd101wyy** [comment]
Hi @tmori3y2 !

Thanks for your contribution!!!
Sorry, I will disappear for a while because I am hunting jobs (life is hard) and working on the vscode one.
I will let you know once I merge your pull request.  

Sincerely

**Comment by tmori3y2** [comment]
Hi @shd101wyy !

No problem.

I understand it.

**Comment by tmori3y2** [comment]
#455

**Comment by shd101wyy** [comment]
@tmori3y2 I don't know if this issue still happenes?

**Comment by tmori3y2** [comment]
Hi @shd101wyy 

No blank areas is there, but graph is too large.

Maybe width is not set, I think.

**Comment by dpo** [comment]
> Well, to be honest I want to abandon atom now as vscode is so much faster...

@shd101wyy Please don't abandon Atom!!! We need you and your fantastic package!

**Comment by kachkaev** [comment]
@shd101wyy how about closing this as stale?

**Comment by kachkaev** [comment]
Closing as out-of-date (the project does not use CoffeeScript any more)

**Pull request closed without merging**
